import { ReactNode } from 'react'

import type { Metadata } from 'next'
import HeaderRegisterOrder from '@/components/HeanderRegisterOrder'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StoreLayout({ children }: { children: ReactNode }) {
  return (
    <div>
      <HeaderRegisterOrder />
      {children}
    </div>
  )
}