import { ReactNode } from 'react'

import type { Metadata } from 'next'
import HeaderEditOrder from '@/components/[id]/HeaderEditOrder'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StoreLayout({ children }: { children: ReactNode }) {
  return (
    <div>
      <HeaderEditOrder />
      {children}
    </div>
  )
}